Brown = "BITE 'EM BEARS"
Columbia = "POWDER BLUE"
Cornell = "PASTURIZE CORNELL"
Dartmouth = "WHOMP 'EM"
Harvard = "PUSEY-LANIMOUS"
Penn = "THROW U.P."
Yale = "{Picture of a fire hydrant}"
URI = "SHAVE THE WOOLIES"
