Columbia = "DICK THE LION-HEARTED"
Cornell = "BEAT THE REAPERS"
Dartmouth = "MOW THE GREEN"
Harvard = "BOK BIER"
Princeton = "FRITZ THE CAT"
Penn = "SHOOT UP"
Yale = "PENALIZE ELI’S"
"Holy Cross" = "EXORCIZE ’EM"
URI = "BUTTON THE MUTTON"
