Columbia = "BROWN-OUT COLUMBIA"
Cornell = "POUND EZRA"
Dartmouth = "SEED THE GREEN"
Harvard = "RECYCLE THE CANTABS"
Princeton = "KITTY KITTY BANG BANG"
Penn = "QUAKER OAFS"
Yale = "{A lock with BROWN on it}"
"Holy Cross" = "NAIL 'EM"
URI = "SCREW EWE"
