Columbia = "SWALLOW THE PRIDE"
Cornell = "CORN(ELL) SHUCKS"
Dartmouth = "BANG GANG-GREEN"
Harvard = "HARVARD BEATS"
Princeton = "CIAO! CIAO! CIAO!"
Penn = "BALL . PENN"
Yale = "SPAY THE DOG"
"Holy Cross" = "BREAK THEIR RHYTHM"
