Columbia = "S.U.N.Y. HARLEM"
Cornell = "UDDER DESTRUCTION"
Dartmouth = "GREEN AND BEAR IT"
Harvard = "MOUNT THE CLIFFIES"
Princeton = "SQUEEZE THE ORANGE"
Penn = "DRILL QUAKER STATE"
Yale = "STRIP THEIR BARK"
"Holy Cross" = "KICK THE HABIT"
URI = "CRAMETTE"
