Columbia = "SMOKE COLUMBIA"
Cornell = "CHEW BIG RED"
Dartmouth = "HAND OVER NEW HAMPSHIRE"
Harvard = "LAMPOON HARVARD"
Princeton = "SQUEEZE THE PUSS"
Penn = "PENN DEMONIUM"
Yale = "DITCH THE BITCH"
"Holy Cross" = "BEAR THE CROSS"
URI = "MUD IN U.R.I."
