Brown = "EVER TRUE TO BROWN"
Columbia = "HOOK LION & SINK ’ER"
Cornell = "RED DIE (NO. 2)"
Dartmouth = "TOSS THE GREENS"
Harvard = "BURN THE BRIGIANS"
Princeton = "CAT ASS TROPHY"
Penn = "BLOW U.P."
Yale = "POUND ’EM"
"Holy Cross" = "ALTAR ’EM"
URI = "EWE LOSE"
