Columbia = "NO PRIDE"
Cornell = "APOCALYPSE COW"
Dartmouth = "SHUT D’MOUTH"
Harvard = "VERI TAS TY"
Princeton = "STOP MEN O’PAWS"
Penn = "POISON PENN"
Yale = "HUSH THE PUPPIES"
"Holy Cross" = "KNOCK WORCESTER"
URI = "LACK OF RAM"
