Columbia = "WEST SIDE GORY"
Cornell = "PART THE RED C"
Dartmouth = "BELITTLE GREEN MEN"
Harvard = "CRIMSON TIED"
Princeton = "SUBORDINATE CLAWS"
Penn = "POLLY WANTS A QUAKER"
Yale = "CURB THE DOGS"
Army = "NUKE ARMY"
"Holy Cross" = "MASS DESTRUCTION"
URI = "BATTER THE RAMS"
