Brown = "BROWN FOREVERMORE"
Columbia = "KING OF THE LEAST"
Cornell = "THIS CUD’S FOR YOU"
Dartmouth = "WASHING DOWN D.C."
Harvard = "COOP d’ETAT"
Princeton = "OLD NAUSEA"
Penn = "BEARS EAT OATS"
Yale = "STRIKE AT YALE"
"Holy Cross" = "LACK OF VIRGIN (HEY!)"
Richmond = "HARLOT’S WEB"
URI = "RHODE PIZZA"
