Brown = "CRUSH THEM DOWN FOR BRUNO AND FOR BROWN"
Columbia = "MANELION IN VAIN"
Cornell = "UDDER HELL"
Dartmouth = "DARTMOUTH GREEN.. But Their Sheep Experienced!"
Harvard = "MOW THE YARD"
Princeton = "BEAR DOWN ON THE PUSSIES"
Penn = "PENN’S TRIPE SUITS"
Yale = "BLUE? BIERED"
"Holy Cross" = "GOT A HANGNAIL?"
Maine = "DISMEMBER THE MAINE"
URI = "URINULL"
