Brown = "Divine Providence"
Columbia = "Lions are clobbered by bears! Oh my!"
Cornell = "www.motel6.edu"
Dartmouth = "Co-Ed"
Harvard = "Harvard is run by Radcliffe"
Princeton = "Daddy, my knees hurt!"
Penn = "Spankin’ Franklin"
Yale = "Skull and boneheads"
Fordham = "For dumb students"
Lafayette = "Who the L are U?"
URI = "Insufficient ram"
