Brown = "250 {Elrod leaning on bass drum “0”}"
"Family Weekend" = "My child joined the Brown Band and all I got was this button."
Hockey = "The Cutting Edge 4: Bruno’s Revenge"
Columbia = "Winning? Too mainstream."
Cornell = "I’ve got a fever, and the only prescription is less Cornell."
Dartmouth = "Worst Hanover I ever had"
Harvard = "{Lowercase letter “h” in Comic Sans font}"
Princeton = "If it’s orange and from New Jersey, it’s probably a douchebag."
Penn = "Join the Penn ‘15 club"
Yale = "Save the Yales"
Georgetown = "Curious Georgetown {Image of Curious George}"
"Holy Cross" = "{Cross made of swiss cheese}"
URI = "Think do. We big."
