Brown = "Blueno"
Hockey = "Give Them Nothing!!!!"
Columbia = "How do I get to Bogotá from here?"
Cornell = "Why so hostel?"
Dartmouth = "Big Green Monsters"
Harvard = "Weed, Not Tweed"
Princeton = "Ted Cruz ’92 is the Zodiac Killer"
Stetson = "Please clap. {picture of Jeb Bush}"
Penn = "You Don’t Deserve Joe Biden"
Yale = "You’ve Got Yale {iOS Mail app icon with 1 unread email}"
Bryant = "Brie Ant"
URI = "“why is rhode island nor a road or an island” @justinbieber"
