URI = "You Are I {two spidermen pointing at each other meme}"
Harvard = "HARBOR EDUCATED {sailboat}"
Bryant = "I can’t believe we got Fulton in the divorce"
Colgate = "haha teeth {picture of teeth}"
Princeton = "{Netflix’s Tiger King with tiger print background}"
Cornell = "“I am forbidden from commenting on Cornell, its neighboring institutions, and the beautiful city of Ithaca.”"
Penn = "“Bad things happen in Philadelphia” — Donald Trump, Class of ‘68"
Yale = "You put the “Eli” in elitist"
Brown = "Brown gives no formal grades, nor does it teach anything"
Columbia = "columbia band has left the chat"
Dartmouth = "I do not like green eggs and Hanover"
Caroling = "[2011 Facebook post by Brown Assistant Director of Athletics John Diamond] Hehe snow in my face"
Hockey = "[handwritten in purple on lined paper] I LOVE UNCRUSTABLES"
