Bryant = "Screaming, Bryant, Throwing Up"
Brown = "{2016 Twitter post by Ben Shapiro} Brown University is legitimately the stupidest place in America."
Harvard = "We Cambridge in your Mass"
CCSU = "Northern Nonnecticut Nate Nooniversity"
URI = "{Valentine's Day Sweetheart} UR Mine"