Bryant = "Screaming, Bryant, Throwing Up"
Brown = "{2016 Twitter post by Ben Shapiro} Brown University is legitimately the stupidest place in America."
Harvard = "We Cambridge in your Mass"
CCSU = "Northern Nonnecticut Nate Nooniversity"
URI = "{Valentine's Day Sweetheart} UR Mine"
Princeton = "{On tiger stripes} Stripes are so Last Season {sassy painted nail emoji}"
Cornell = "Big Red Sus {red Amongus character}"
Penn = "She Philly my Delphi till I A"
Yale = "Most handsome Yale student {picture of Handsome Dan}"
Columbia = "Why you always lion?"
Dartmouth = "What dart mouth do?"