Georgetown = "{Face of Bass Drum Player George Chudley} Town"
Bryant = "{Bryan from Family Guy getting hit by a Prius}"
Brown = "{Picture of the Perelman Arts District Map} Perelman Arts University"
Harvard = "{Picture of Turnitin 100% Plagiarism Match}"
URI = "{Photo of Terminator} The Urinator"
Princeton = "Ivy Madness 90 - 81 {Photo of Xavian Lee, Princeton Point Guard 2024}"
Cornell = "Nice Mascot, How Original"
Penn = "{Donald Trump 2023 Mugshot}"
Yale = "I Got that Dog in Me {Picture of Handsome Dan}"
Columbia = "Long Live the King {Photo of Mufasa Falling off Cliff}"
Dartmouth = "Green Kegs and Lamb"
Hockey = "Watch Out! The Ice is Slippery!"
Caroling = "So Much for a Silent Night!"