[[unknown]]
about = "???"
imageName = 17
label = "MASS ACHERS"

[[unknown]]
about = "???"
imageName = 71
label = "JOIN THE CROWD! BROWN FOOTBALL"

[[unknown]]
about = "???"
imageName = 75
label = "{treble clef}"

[[unknown]]
about = "Brown, 2003"
imageName = 100
label = "BROWN FOOTBALL 125th Anniversary"

[[unknown]]
about = "Brown, ???"
imageName = 101
label = "{B} HOCKEY"

[[unknown]]
about = "Hockey"
imageName = 357
label = "Watch Out! The Ice is Slippery!"

[[unknown]]
about = "Hockey"
label = "Stick it in, Bruno!"

[[unknown]]
about = "???"
imageName = 373
label = "My Child Joined THE BROWN BAND and All I Got Was This Lousy Button"

[[unknown]]
about = "Harvard, 1967?"
label = "POP THE CANTABS"

[[unknown]]
about = "Yale, 1967? 1968?"
label = "ELIS'LL DOLITTLE"

[[unknown]]
about = 1993
label = "BCO DAY 1993"

[[unknown]]
about = "Penn, 2007 (replaced)"
label = "Sorry! We forgot about you"

[[unknown]]
about = "Cornell/Harvard/Penn, pre-1992"
label = "George Bush's Worst Nightmare"
