name: GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store/
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ hashFiles('pnpm-lock.yaml') }}
            pnpm-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.6

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Eleventy
        run: pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload built site to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      # - name: Tar built website
      #   run: tar -cvvf public.tar.gz public/

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: gh-pages-${{ github.sha }}
      #     path: public.tar.gz

      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v1
