name: GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - run: npm ci
      - run: npm run build

      - name: Upload Built Site
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: public/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
