name: GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # speeds up pnpm install, theoretically
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm7-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm7-${{ hashFiles('pnpm-lock.yaml') }}
            pnpm7-

      - name: Setup PNPM
        id: pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.12.2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Eleventy
        run: pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: Eleventy:Benchmark

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/
          retention-days: 90
