name: GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store/
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('package.json') }}
          restore-keys: pnpm-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Eleventy
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tar built website
        run: tar -cvvf public.tar.gz public/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages-${{ github.sha }}
          path: public.tar.gz

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
